<div class="row">
    <div class="col-xs-12 col-sm-4 text-center">
        <div class="img-perfil w-100">
            <img class="img-circle" src="https://www.movilidadbogota.gov.co/web/sites/default/files/Paginas/23-09-2020/johana-catalina-latorre.jpg" alt="">
        </div>
    </div>
    <div class="col-xs-12 col-sm-8 ">
        <div class="descripcion">
            <h1>Johana Catalina Latorre Alarcón</h1>
            <h4>Subdirectora de Contravenciones</h4>
            <div class="descripcion-xs">
                <p>Es abogada egresada de la Universidad Pedagógica y Tecnológica de Colombia - UPTC, especialista en Derecho Urbano de la Universidad del Rosario, y Magíster en Derecho de la Universidad Sergio Arboleda, con más de seis años de experiencia en el sector público, en la sustanciación de procesos administrativos, sancionatorios, de sometimiento a control y de responsabilidad fiscal.</p>
                <p>Su mayor desafío en los actuales momentos de emergencia sanitaria, es coordinar su equipo para prestar al ciudadano un servicio eficiente y oportuno dentro del regreso a la “Nueva Normalidad”.</p>
            </div>
        </div>
    </div>
</div>
